package com.mycompany.daytypeprogram;

public class DayTypeProgram extends javax.swing.JFrame {

    public String dayToPrint = "";
    /**
     * Creates new form DayTypeProgram
     */
    public DayTypeProgram() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxDay = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        setDayButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        addDays = new javax.swing.JButton();
        subtractDays = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        daySpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DayType");
        setPreferredSize(new java.awt.Dimension(417, 250));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Choose day:");

        comboBoxDay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" }));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        setDayButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        setDayButton.setText("Set Day");
        setDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDayButtonActionPerformed(evt);
            }
        });

        prevButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        prevButton.setText("Prev");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        nextButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        printButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        addDays.setText("+");
        addDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDaysActionPerformed(evt);
            }
        });

        subtractDays.setText("-");
        subtractDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractDaysActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("No. of Days:");

        daySpinner.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Made by: REDACTED");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(daySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addDays, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subtractDays, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prevButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setDayButton)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prevButton)
                        .addGap(9, 9, 9)
                        .addComponent(nextButton)
                        .addGap(9, 9, 9)
                        .addComponent(printButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDays)
                    .addComponent(subtractDays)
                    .addComponent(jLabel2)
                    .addComponent(daySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /*
    how to use:
    1. select a day from the combo box, and press the set day button
    2. press any of the of the prev, next, plus and minus buttons
    3. press print button last
    4. to use the no. of days option, change the value of the spinner first
       and then press either the plus or minus button.
       press the print button last.
    */
    
    DayType d = new DayType();
    
    /* 
    sets the value of the instance variable day to that of the value
    in the combo box.
    */
    private void setDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDayButtonActionPerformed
        d.setDay(d.getDay());
        dayToPrint = (String) comboBoxDay.getSelectedItem();
        System.out.println("Day value set. Current day: " + comboBoxDay.getSelectedItem());
    }//GEN-LAST:event_setDayButtonActionPerformed

    /*
    this gets the previous day before the current day value.
    doesn't print anything.
    */
    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        d.setDay((String) comboBoxDay.getSelectedItem());
        dayToPrint = d.previousDay();
        System.out.println("Set to previous day. Current day: " + comboBoxDay.getSelectedItem());
    }//GEN-LAST:event_prevButtonActionPerformed
    
    /*
    this gets the next day after the current day value.
    doesn't print anything.
    */
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        d.setDay((String) comboBoxDay.getSelectedItem());
        dayToPrint = d.nextDay();
        System.out.println("Set to next day. Current day: " + comboBoxDay.getSelectedItem());
    }//GEN-LAST:event_nextButtonActionPerformed

    /*
    prints the current value stored. this needs to be pressed last after 
    all the other buttons in order to display the result in the text box.
    */
    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        textArea.setText(dayToPrint);
        System.out.println("Printed!");
    }//GEN-LAST:event_printButtonActionPerformed

    // the "+" button
    private void addDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDaysActionPerformed
        d.setDay((String) comboBoxDay.getSelectedItem());
        int dayFromTodayInt = (Integer) daySpinner.getValue();
        dayToPrint = d.addDays(dayFromTodayInt);
        if (dayFromTodayInt == 1) {
            System.out.println("Value is set to be 1 day ahead of current day");
        } else {
            System.out.println("Value is set to be " + dayFromTodayInt + " days ahead of current day");
        }  
    }//GEN-LAST:event_addDaysActionPerformed

    // the "-" button
    private void subtractDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractDaysActionPerformed
        d.setDay((String) comboBoxDay.getSelectedItem());
        int dayBeforeTodayInt = (Integer) daySpinner.getValue();
        dayToPrint = d.subDays((Integer) daySpinner.getValue());
        System.out.println("Value is set to be " + dayBeforeTodayInt + " days before current day");
        if (dayBeforeTodayInt == 1) {
            System.out.println("Value is set to be 1 day before current day");
        } else {
            System.out.println("Value is set to be " + dayBeforeTodayInt + " days before current day");
        } 
    }//GEN-LAST:event_subtractDaysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DayTypeProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DayTypeProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DayTypeProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DayTypeProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DayTypeProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDays;
    private javax.swing.JComboBox<String> comboBoxDay;
    private javax.swing.JSpinner daySpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JButton printButton;
    private javax.swing.JButton setDayButton;
    private javax.swing.JButton subtractDays;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
